tasks:
  - name: Setup Java and Maven
    init: |
      sudo apt-get update
      sudo apt-get install -y openjdk-17-jdk maven
    command: mvn exec:java -Dexec.mainClass="learn.test2.CloudTest2"

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - VisualStudioExptTeam.vscodeintellicode
